# An example configuration:
#FedeTibaldo:
#  CkStyles:
#    InlineStyles:
#      presets:
#        'fontColor':
#          label: 'Font color'
#          options:
#            'primary':
#              label: 'Red'
#              cssClass: 'my-class-red'
#            'secondary':
#              label: 'Green'
#              cssClass: 'my-class-green'
#            '':
#              label: 'unset color'
#              cssClass: null
#        'fontSize':
#          label: 'Font size'
#          options:
#            'small':
#              label: 'Small'
#              cssClass: 'my-class-size-small'
#            'big':
#              label: 'Large'
#              cssClass: 'my-class-size-large'
#            '':
#              label: 'unset size'
#              cssClass: null

Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'FedeTibaldo.CkStyles:Styles':
            resource: resource://FedeTibaldo.CkStyles/Public/JavaScript/CkStyles/Plugin.js
      frontendConfiguration:
        'FedeTibaldo.CkStyles:InlineStyles': '${Configuration.setting(''FedeTibaldo.CkStyles.InlineStyles'')}'
        'FedeTibaldo.CkStyles:BlockStyles': '${Configuration.setting(''FedeTibaldo.CkStyles.BlockStyles'')}'
